"""200 hand-written problem-solution examples for TD MHN.

Each example is a (problem_text, solution, domain, task_type) tuple.
When loaded into the decomposer's MHN, these give TD memory —
it can retrieve relevant past solutions for new problems.

Categories:
    Scheduling (50)
    Budget/Allocation (30)
    Logic/Proof (25)
    Math/Optimization (20)
    Code/Debugging (20)
    Data/Parsing (20)
    Transformation (15)
    Planning (10)
    Validation (10)

Total: 200
"""

EXAMPLES: list[tuple[str, dict, str, str]] = [
    # =====================================================================
    # SCHEDULING (50)
    # =====================================================================
    ("Schedule a team meeting next Tuesday at 2pm",
     {"action": "book", "time": "Tuesday 2pm", "type": "team_meeting"},
     "scheduling", "meeting"),
    ("Find a time when all 5 team members are available",
     {"action": "find_slots", "method": "calendar_intersection"},
     "scheduling", "availability"),
    ("Book a meeting with Alice and Bob next week",
     {"action": "book", "participants": ["Alice", "Bob"], "week": "next"},
     "scheduling", "meeting"),
    ("Schedule 3 interviews for the candidate panel",
     {"action": "schedule", "count": 3, "type": "interview"},
     "scheduling", "meeting"),
    ("Reschedule the Friday meeting to Monday",
     {"action": "reschedule", "from": "Friday", "to": "Monday"},
     "scheduling", "reschedule"),
    ("Find available conference rooms for next Thursday",
     {"action": "find", "target": "conference_room", "day": "Thursday"},
     "scheduling", "resource"),
    ("Coordinate meeting times across 3 time zones",
     {"action": "coordinate", "zones": 3, "method": "timezone_overlap"},
     "scheduling", "meeting"),
    ("Set up a recurring weekly sync every Monday morning",
     {"action": "recurring", "frequency": "weekly", "day": "Monday"},
     "scheduling", "recurring"),
    ("Schedule a client call avoiding Friday afternoon",
     {"action": "book", "type": "client_call", "avoid": "Friday afternoon"},
     "scheduling", "meeting"),
    ("Find the earliest time all managers can meet",
     {"action": "find_earliest", "method": "earliest_intersection"},
     "scheduling", "availability"),
    ("Book the boardroom for the quarterly review",
     {"action": "book", "room": "boardroom", "type": "quarterly_review"},
     "scheduling", "resource"),
    ("Resolve double booking between sales and engineering meetings",
     {"action": "resolve", "conflict": "double_booking"},
     "scheduling", "conflict"),
    ("Schedule sprint planning for the development team",
     {"action": "schedule", "type": "sprint_planning"},
     "scheduling", "task"),
    ("Arrange a product demo for the client next week",
     {"action": "arrange", "type": "demo", "timing": "next_week"},
     "scheduling", "meeting"),
    ("Find a time for the all-hands meeting this month",
     {"action": "find_slots", "type": "all_hands"},
     "scheduling", "meeting"),
    ("Schedule performance reviews for all team members",
     {"action": "schedule", "type": "performance_review", "batch": True},
     "scheduling", "task"),
    ("Book travel time between the office and client site",
     {"action": "book", "type": "travel_time"},
     "scheduling", "travel"),
    ("Reserve equipment for the training session",
     {"action": "reserve", "target": "equipment", "type": "training"},
     "scheduling", "resource"),
    ("Schedule a backup meeting in case the first one is canceled",
     {"action": "schedule", "type": "backup_meeting"},
     "scheduling", "contingency"),
    ("Find overlap between Alice calendar and Bob calendar",
     {"action": "find", "method": "calendar_overlap"},
     "scheduling", "availability"),
    ("Schedule 5 meetings this week without conflicts",
     {"action": "schedule", "count": 5, "constraint": "no_conflicts"},
     "scheduling", "meeting"),
    ("Prioritize client calls over internal meetings",
     {"action": "prioritize", "high": "client_calls", "low": "internal"},
     "scheduling", "priority"),
    ("Avoid scheduling meetings during lunch hour",
     {"action": "avoid", "slot": "lunch_hour"},
     "scheduling", "constraint"),
    ("Schedule shifts for the support team next week",
     {"action": "schedule", "type": "shift", "team": "support"},
     "scheduling", "shift"),
    ("Find the best time for a cross-team workshop",
     {"action": "find", "type": "workshop", "method": "cross_team"},
     "scheduling", "meeting"),
    ("Schedule a doctor appointment next week",
     {"action": "book", "type": "appointment"},
     "scheduling", "appointment"),
    ("Reserve study room in the library for exam prep",
     {"action": "reserve", "target": "study_room"},
     "scheduling", "resource"),
    ("Book a flight to Istanbul departing Tuesday morning",
     {"action": "book", "type": "flight", "destination": "Istanbul"},
     "scheduling", "travel"),
    ("Plan a 3-day conference schedule with 50 sessions",
     {"action": "plan", "type": "conference", "sessions": 50},
     "scheduling", "planning"),
    ("Schedule dentist appointment around work meetings",
     {"action": "schedule", "type": "appointment", "constraint": "around_work"},
     "scheduling", "appointment"),
    ("Find time for urgent meeting today",
     {"action": "find", "urgency": "urgent", "day": "today"},
     "scheduling", "meeting"),
    ("Schedule code review session with the team",
     {"action": "schedule", "type": "code_review"},
     "scheduling", "meeting"),
    ("Book hotel for the business trip next month",
     {"action": "book", "type": "hotel", "timing": "next_month"},
     "scheduling", "travel"),
    ("Coordinate volunteer shifts for the event",
     {"action": "coordinate", "type": "volunteer_shift"},
     "scheduling", "shift"),
    ("Schedule a make-up exam for the student",
     {"action": "schedule", "type": "exam", "variant": "makeup"},
     "scheduling", "exam"),
    ("Find meeting time that works for remote and in-office staff",
     {"action": "find", "constraint": "remote_and_office"},
     "scheduling", "meeting"),
    ("Schedule a follow-up meeting after the client demo",
     {"action": "schedule", "type": "follow_up"},
     "scheduling", "meeting"),
    ("Reschedule all meetings affected by the holiday",
     {"action": "reschedule", "reason": "holiday"},
     "scheduling", "reschedule"),
    ("Schedule daily standup at 9am",
     {"action": "schedule", "type": "standup", "time": "9am"},
     "scheduling", "recurring"),
    ("Find available proctors for the final exam",
     {"action": "find", "target": "proctor", "type": "exam"},
     "scheduling", "resource"),
    ("Schedule a lunch meeting with the vendor",
     {"action": "schedule", "type": "lunch_meeting"},
     "scheduling", "meeting"),
    ("Plan the release schedule for 3 features",
     {"action": "plan", "type": "release_schedule"},
     "scheduling", "planning"),
    ("Schedule training sessions for new employees",
     {"action": "schedule", "type": "training", "audience": "new_hires"},
     "scheduling", "task"),
    ("Book a meeting room with projector for the presentation",
     {"action": "book", "resource": "projector", "type": "presentation"},
     "scheduling", "resource"),
    ("Find time slot for emergency team meeting",
     {"action": "find", "urgency": "emergency"},
     "scheduling", "meeting"),
    ("Schedule weekly one-on-ones with each team member",
     {"action": "schedule", "type": "one_on_one", "frequency": "weekly"},
     "scheduling", "recurring"),
    ("Reserve lab time for the physics experiment",
     {"action": "reserve", "target": "lab"},
     "scheduling", "resource"),
    ("Schedule the project kickoff meeting",
     {"action": "schedule", "type": "kickoff"},
     "scheduling", "meeting"),
    ("Arrange meeting with stakeholders for budget approval",
     {"action": "arrange", "type": "budget_approval"},
     "scheduling", "meeting"),
    ("Schedule end of sprint retrospective",
     {"action": "schedule", "type": "retrospective"},
     "scheduling", "meeting"),

    # =====================================================================
    # BUDGET / ALLOCATION (30)
    # =====================================================================
    ("Allocate $10000 budget across 5 departments",
     {"action": "allocate", "total": 10000, "departments": 5},
     "budget", "allocation"),
    ("Find the cheapest way to allocate resources",
     {"action": "optimize", "objective": "minimize_cost"},
     "budget", "optimization"),
    ("Distribute $5000 among marketing sales and engineering",
     {"action": "distribute", "amount": 5000},
     "budget", "allocation"),
    ("Cut 15 percent from the operational budget",
     {"action": "cut", "percentage": 15},
     "budget", "cut"),
    ("Balance income and expenses for the quarter",
     {"action": "balance", "period": "quarter"},
     "budget", "balancing"),
    ("Optimize return on investment portfolio",
     {"action": "optimize", "target": "ROI"},
     "budget", "investment"),
    ("Allocate budget to maximize project impact",
     {"action": "allocate", "objective": "maximize_impact"},
     "budget", "allocation"),
    ("Plan budget for the next fiscal year",
     {"action": "plan", "period": "fiscal_year"},
     "budget", "planning"),
    ("Reduce cloud spending by 20 percent",
     {"action": "reduce", "target": "cloud_cost", "percentage": 20},
     "budget", "cut"),
    ("Split the grant among 3 research projects",
     {"action": "split", "source": "grant", "recipients": 3},
     "budget", "grant"),
    ("Calculate cost per unit for the manufacturing line",
     {"action": "calculate", "metric": "cost_per_unit"},
     "budget", "analysis"),
    ("Forecast quarterly expenses based on historical data",
     {"action": "forecast", "period": "quarter"},
     "budget", "forecasting"),
    ("Compare vendor pricing for the same service",
     {"action": "compare", "target": "vendor_pricing"},
     "budget", "comparison"),
    ("Identify cost saving opportunities in the supply chain",
     {"action": "identify", "target": "cost_savings"},
     "budget", "optimization"),
    ("Allocate team members to projects based on skills",
     {"action": "allocate", "criterion": "skills"},
     "allocation", "resource"),
    ("Assign classrooms to courses minimizing gaps",
     {"action": "assign", "target": "classroom"},
     "allocation", "resource"),
    ("Distribute workloads evenly across servers",
     {"action": "distribute", "target": "workload"},
     "allocation", "resource"),
    ("Allocate memory between applications fairly",
     {"action": "allocate", "target": "memory"},
     "allocation", "resource"),
    ("Assign tasks to workers based on availability",
     {"action": "assign", "criterion": "availability"},
     "allocation", "task"),
    ("Divide the advertising budget across 4 channels",
     {"action": "divide", "channels": 4},
     "budget", "allocation"),
    ("Minimize total project cost within quality constraints",
     {"action": "minimize", "target": "project_cost"},
     "budget", "optimization"),
    ("Reconcile budget after unexpected expenses",
     {"action": "reconcile", "reason": "unexpected_expenses"},
     "budget", "balancing"),
    ("Estimate cost of the construction project",
     {"action": "estimate", "target": "construction_cost"},
     "budget", "forecasting"),
    ("Optimize staffing to minimize overtime cost",
     {"action": "optimize", "target": "overtime_cost"},
     "allocation", "optimization"),
    ("Allocate server resources dynamically based on traffic",
     {"action": "allocate", "method": "dynamic"},
     "allocation", "resource"),
    ("Plan personal monthly budget with rent utilities food",
     {"action": "plan", "categories": ["rent", "utilities", "food"]},
     "budget", "planning"),
    ("Award scholarship funds to top 10 candidates",
     {"action": "award", "target": "scholarship", "count": 10},
     "budget", "grant"),
    ("Distribute bonuses based on performance ratings",
     {"action": "distribute", "target": "bonus", "criterion": "performance"},
     "allocation", "budget"),
    ("Calculate break even point for the new product",
     {"action": "calculate", "metric": "break_even"},
     "budget", "analysis"),
    ("Optimize inventory levels to minimize holding cost",
     {"action": "optimize", "target": "inventory_cost"},
     "budget", "optimization"),

    # =====================================================================
    # LOGIC / PROOF (25)
    # =====================================================================
    ("Prove that if A implies B and B implies C then A implies C",
     {"action": "prove", "method": "hypothetical_syllogism"},
     "proof", "logical"),
    ("Show that the sum of two even numbers is even",
     {"action": "prove", "target": "even_sum_property"},
     "proof", "induction"),
    ("Prove by contradiction that the square root of 2 is irrational",
     {"action": "prove", "method": "contradiction", "target": "sqrt2_irrational"},
     "proof", "contradiction"),
    ("Verify that the sorting algorithm terminates for all inputs",
     {"action": "verify", "target": "termination"},
     "proof", "correctness"),
    ("Prove by induction that sum of first n integers is n times n+1 over 2",
     {"action": "prove", "method": "induction"},
     "proof", "induction"),
    ("Show that the algorithm maintains the loop invariant",
     {"action": "show", "target": "loop_invariant"},
     "proof", "program"),
    ("Prove that the binary search is correct",
     {"action": "prove", "target": "binary_search_correctness"},
     "proof", "program"),
    ("Deduce the conclusion from the given premises",
     {"action": "deduce", "method": "inference_rules"},
     "proof", "logical"),
    ("Prove that the function is injective",
     {"action": "prove", "property": "injective"},
     "proof", "existence"),
    ("Show uniqueness of the solution",
     {"action": "show", "property": "uniqueness"},
     "proof", "uniqueness"),
    ("Prove the contrapositive of the statement",
     {"action": "prove", "method": "contrapositive"},
     "proof", "contrapositive"),
    ("Verify the security of the cryptographic protocol",
     {"action": "verify", "target": "security"},
     "proof", "security"),
    ("Prove that the set of primes is infinite",
     {"action": "prove", "target": "infinite_primes"},
     "proof", "contradiction"),
    ("Show that the relation is an equivalence relation",
     {"action": "show", "property": "equivalence"},
     "proof", "logical"),
    ("Prove correctness of the greedy algorithm",
     {"action": "prove", "target": "greedy_correctness"},
     "proof", "correctness"),
    ("Check logical consistency of the knowledge base",
     {"action": "check", "target": "consistency"},
     "proof", "logical"),
    ("Prove that the matrix is positive definite",
     {"action": "prove", "property": "positive_definite"},
     "proof", "logical"),
    ("Verify the program satisfies its Hoare triple",
     {"action": "verify", "method": "hoare_logic"},
     "proof", "program"),
    ("Prove the theorem using natural deduction",
     {"action": "prove", "method": "natural_deduction"},
     "proof", "logical"),
    ("Show that P equals NP would imply fast solutions",
     {"action": "show", "target": "P_NP_implication"},
     "proof", "logical"),
    ("Prove that the graph is Hamiltonian",
     {"action": "prove", "property": "hamiltonian"},
     "proof", "existence"),
    ("Demonstrate that the protocol achieves zero knowledge",
     {"action": "demonstrate", "property": "zero_knowledge"},
     "proof", "security"),
    ("Prove the completeness of the proof system",
     {"action": "prove", "property": "completeness"},
     "proof", "completeness"),
    ("Check if the argument form is valid",
     {"action": "check", "target": "validity"},
     "proof", "logical"),
    ("Prove by construction that a solution exists",
     {"action": "prove", "method": "constructive"},
     "proof", "existence"),

    # =====================================================================
    # MATH / OPTIMIZATION (20)
    # =====================================================================
    ("Solve the equation 2x plus 5 equals 15",
     {"action": "solve", "equation": "2x+5=15"},
     "math", "algebra"),
    ("Find the minimum of x squared plus y squared",
     {"action": "minimize", "function": "x^2+y^2"},
     "math", "optimization"),
    ("Solve the system of linear equations",
     {"action": "solve", "type": "linear_system"},
     "math", "algebra"),
    ("Maximize profit given price and cost constraints",
     {"action": "maximize", "target": "profit"},
     "math", "optimization"),
    ("Find the shortest path in the weighted graph",
     {"action": "find", "method": "shortest_path"},
     "math", "optimization"),
    ("Calculate the probability of getting at least 3 heads in 5 flips",
     {"action": "calculate", "method": "binomial_probability"},
     "math", "probability"),
    ("Compute the mean and standard deviation of the dataset",
     {"action": "compute", "metrics": ["mean", "std"]},
     "math", "statistics"),
    ("Factor the polynomial x squared minus 4",
     {"action": "factor", "expression": "x^2-4"},
     "math", "algebra"),
    ("Find all prime numbers up to 100",
     {"action": "find", "method": "sieve"},
     "math", "number_theory"),
    ("Optimize the linear program with 3 variables",
     {"action": "optimize", "type": "linear_program"},
     "math", "optimization"),
    ("Solve the differential equation",
     {"action": "solve", "type": "differential"},
     "math", "calculus"),
    ("Compute the integral of x squared from 0 to 1",
     {"action": "compute", "type": "definite_integral"},
     "math", "calculus"),
    ("Find the derivative of x cubed",
     {"action": "find", "type": "derivative"},
     "math", "calculus"),
    ("Calculate the area of the triangle",
     {"action": "calculate", "target": "area"},
     "math", "geometry"),
    ("Perform linear regression on the dataset",
     {"action": "perform", "method": "linear_regression"},
     "math", "statistics"),
    ("Minimize travel distance for the delivery route",
     {"action": "minimize", "target": "travel_distance"},
     "math", "optimization"),
    ("Solve the quadratic equation",
     {"action": "solve", "type": "quadratic"},
     "math", "algebra"),
    ("Find the eigenvalues of the matrix",
     {"action": "find", "target": "eigenvalues"},
     "math", "algebra"),
    ("Compute the correlation between two variables",
     {"action": "compute", "metric": "correlation"},
     "math", "statistics"),
    ("Optimize the knapsack problem with 50 items",
     {"action": "optimize", "type": "knapsack"},
     "math", "optimization"),

    # =====================================================================
    # CODE / DEBUGGING (20)
    # =====================================================================
    ("Debug why the function returns wrong result for negative inputs",
     {"action": "debug", "symptom": "wrong_result", "condition": "negative"},
     "debugging", "logic_error"),
    ("Fix the null pointer exception in the user service",
     {"action": "fix", "error": "null_pointer"},
     "debugging", "runtime_error"),
    ("Find off by one error in the loop boundary",
     {"action": "find", "type": "off_by_one"},
     "debugging", "logic_error"),
    ("Trace the stack trace to find the crash location",
     {"action": "trace", "target": "stack_trace"},
     "debugging", "runtime_error"),
    ("Identify the memory leak in the long running process",
     {"action": "identify", "type": "memory_leak"},
     "debugging", "runtime_error"),
    ("Fix the infinite loop in the recursive function",
     {"action": "fix", "bug": "infinite_loop"},
     "debugging", "logic_error"),
    ("Debug the race condition in the multi threaded code",
     {"action": "debug", "type": "race_condition"},
     "debugging", "logic_error"),
    ("Find why the API returns 500 error",
     {"action": "find", "error": "500"},
     "debugging", "runtime_error"),
    ("Review code for potential security vulnerabilities",
     {"action": "review", "target": "security"},
     "code", "review"),
    ("Write unit tests for the authentication module",
     {"action": "write", "target": "unit_tests"},
     "code", "test"),
    ("Analyze time complexity of the merge sort algorithm",
     {"action": "analyze", "metric": "time_complexity"},
     "code", "complexity"),
    ("Refactor the god class into smaller components",
     {"action": "refactor", "smell": "god_class"},
     "code", "review"),
    ("Check test coverage for the payment module",
     {"action": "check", "metric": "test_coverage"},
     "code", "test"),
    ("Debug why the test fails on CI but passes locally",
     {"action": "debug", "symptom": "ci_only_failure"},
     "debugging", "environment"),
    ("Fix the type error in the generic function",
     {"action": "fix", "error": "type_error"},
     "debugging", "logic_error"),
    ("Identify dead code in the legacy module",
     {"action": "identify", "target": "dead_code"},
     "code", "review"),
    ("Write integration tests for the API endpoints",
     {"action": "write", "type": "integration_tests"},
     "code", "test"),
    ("Debug the connection timeout to the database",
     {"action": "debug", "symptom": "connection_timeout"},
     "debugging", "runtime_error"),
    ("Optimize the slow database query",
     {"action": "optimize", "target": "slow_query"},
     "code", "optimization"),
    ("Review the pull request for edge cases",
     {"action": "review", "target": "pull_request"},
     "code", "review"),

    # =====================================================================
    # DATA / PARSING (20)
    # =====================================================================
    ("Parse the CSV file and extract all rows",
     {"action": "parse", "format": "CSV"},
     "parsing", "structured"),
    ("Read the JSON configuration file",
     {"action": "read", "format": "JSON"},
     "parsing", "structured"),
    ("Load YAML file and validate its structure",
     {"action": "load", "format": "YAML"},
     "parsing", "structured"),
    ("Extract names and emails from the text file",
     {"action": "extract", "fields": ["name", "email"]},
     "parsing", "natural"),
    ("Clean missing values from the dataset",
     {"action": "clean", "issue": "missing_values"},
     "data", "cleaning"),
    ("Remove duplicate records from the customer table",
     {"action": "remove", "target": "duplicates"},
     "data", "cleaning"),
    ("Normalize the date formats across all records",
     {"action": "normalize", "field": "date"},
     "data", "cleaning"),
    ("Aggregate sales data by region and quarter",
     {"action": "aggregate", "keys": ["region", "quarter"]},
     "data", "aggregation"),
    ("Join the orders table with the customers table",
     {"action": "join", "tables": ["orders", "customers"]},
     "data", "join"),
    ("Filter records where status equals active",
     {"action": "filter", "condition": "status=active"},
     "data", "filtering"),
    ("Count how many users have premium subscription",
     {"action": "count", "condition": "premium=true"},
     "data", "counting"),
    ("Sort products by price in descending order",
     {"action": "sort", "key": "price", "order": "descending"},
     "data", "sorting"),
    ("Search for products matching the keyword",
     {"action": "search", "type": "keyword"},
     "data", "search"),
    ("Group customers by purchase frequency",
     {"action": "group", "criterion": "purchase_frequency"},
     "data", "grouping"),
    ("Parse XML and extract attribute values",
     {"action": "parse", "format": "XML"},
     "parsing", "structured"),
    ("Identify outliers in the sensor data",
     {"action": "identify", "target": "outliers"},
     "data", "cleaning"),
    ("Summarize the dataset with descriptive statistics",
     {"action": "summarize", "metrics": "descriptive"},
     "data", "aggregation"),
    ("Merge two CSV files on the ID column",
     {"action": "merge", "key": "ID"},
     "data", "join"),
    ("Validate that all required columns exist in the dataset",
     {"action": "validate", "target": "columns"},
     "validation", "schema"),
    ("Convert the timestamp to ISO 8601 format",
     {"action": "convert", "target": "timestamp"},
     "transformation", "format"),

    # =====================================================================
    # TRANSFORMATION (15)
    # =====================================================================
    ("Convert JSON to CSV format with specific column mapping",
     {"action": "convert", "from": "JSON", "to": "CSV"},
     "transformation", "format"),
    ("Transform the data to match the new schema",
     {"action": "transform", "target": "schema"},
     "transformation", "data"),
    ("Export the filtered results to a new file",
     {"action": "export"},
     "transformation", "format"),
    ("Normalize all text to lowercase",
     {"action": "normalize", "transform": "lowercase"},
     "transformation", "data"),
    ("Map source fields to target format fields",
     {"action": "map", "type": "field_mapping"},
     "transformation", "data"),
    ("Convert temperature from Fahrenheit to Celsius",
     {"action": "convert", "metric": "temperature"},
     "transformation", "data"),
    ("Standardize phone numbers to international format",
     {"action": "standardize", "field": "phone"},
     "transformation", "data"),
    ("Generate a CSV report from the database query",
     {"action": "generate", "format": "CSV"},
     "transformation", "format"),
    ("Apply currency conversion to all amounts",
     {"action": "apply", "transform": "currency_conversion"},
     "transformation", "data"),
    ("Compress the image without losing quality",
     {"action": "compress", "target": "image"},
     "transformation", "data"),
    ("Convert the video to MP4 format",
     {"action": "convert", "to": "MP4"},
     "transformation", "format"),
    ("Encrypt the sensitive data fields",
     {"action": "encrypt", "target": "sensitive_fields"},
     "transformation", "data"),
    ("Decode the base64 encoded string",
     {"action": "decode", "encoding": "base64"},
     "transformation", "data"),
    ("Flatten the nested JSON structure",
     {"action": "flatten", "target": "nested_json"},
     "transformation", "data"),
    ("Pivot the table from long to wide format",
     {"action": "pivot", "direction": "long_to_wide"},
     "transformation", "data"),

    # =====================================================================
    # PLANNING (10)
    # =====================================================================
    ("Plan a step by step approach to launch the startup",
     {"action": "plan", "type": "launch"},
     "planning", "sequential"),
    ("Create a project roadmap for the next 6 months",
     {"action": "create", "type": "roadmap"},
     "planning", "sequential"),
    ("Design a contingency plan for server failure",
     {"action": "design", "type": "contingency"},
     "planning", "conditional"),
    ("Plan the migration from monolith to microservices",
     {"action": "plan", "type": "migration"},
     "planning", "sequential"),
    ("Develop a backup plan for data recovery",
     {"action": "develop", "type": "backup_plan"},
     "planning", "conditional"),
    ("Create a study plan for the final exam week",
     {"action": "create", "type": "study_plan"},
     "planning", "sequential"),
    ("Plan the marketing campaign for product launch",
     {"action": "plan", "type": "marketing"},
     "planning", "sequential"),
    ("Design an onboarding workflow for new hires",
     {"action": "design", "type": "onboarding"},
     "planning", "sequential"),
    ("Plan the deployment pipeline for continuous delivery",
     {"action": "plan", "type": "deployment"},
     "planning", "sequential"),
    ("Create a fallback plan if the primary vendor fails",
     {"action": "create", "type": "fallback"},
     "planning", "conditional"),

    # =====================================================================
    # VALIDATION (10)
    # =====================================================================
    ("Validate the form fields are all filled correctly",
     {"action": "validate", "target": "form"},
     "validation", "schema"),
    ("Check data integrity after the migration",
     {"action": "check", "target": "data_integrity"},
     "validation", "logic"),
    ("Verify the user has required permissions",
     {"action": "verify", "target": "permissions"},
     "validation", "logic"),
    ("Ensure all required fields are present in the JSON",
     {"action": "ensure", "target": "required_fields"},
     "validation", "schema"),
    ("Check for duplicate entries in the database",
     {"action": "check", "target": "duplicates"},
     "validation", "logic"),
    ("Validate email format for all user records",
     {"action": "validate", "field": "email"},
     "validation", "schema"),
    ("Confirm the password meets complexity requirements",
     {"action": "confirm", "target": "password_complexity"},
     "validation", "schema"),
    ("Verify the checksum of the downloaded file",
     {"action": "verify", "target": "checksum"},
     "validation", "logic"),
    ("Check referential integrity in the relational database",
     {"action": "check", "target": "referential_integrity"},
     "validation", "logic"),
    ("Ensure the configuration file has no syntax errors",
     {"action": "ensure", "target": "config_syntax"},
     "validation", "schema"),
]

assert len(EXAMPLES) == 200, f"Expected 200 examples, got {len(EXAMPLES)}"
